import { ChallengeConfig } from '../models/game.models';

export const CHALLENGE_DEFINITIONS: ChallengeConfig[] = [
  {
    id: 'speed_click_1',
    name: 'Speed Scan',
    description: 'Click 50 packages in 10 seconds!',
    icon: '\u{23F1}\u{FE0F}',
    type: 'speed_click',
    durationMs: 10000,
    target: 50,
    reward: { expressPoints: 10 },
  },
  {
    id: 'speed_click_2',
    name: 'Turbo Scanner',
    description: 'Click 100 packages in 10 seconds!',
    icon: '\u{23F1}\u{FE0F}',
    type: 'speed_click',
    durationMs: 10000,
    target: 100,
    reward: { expressPoints: 25 },
  },
  {
    id: 'speed_click_3',
    name: 'Lightning Fingers',
    description: 'Click 200 packages in 15 seconds!',
    icon: '\u{26A1}',
    type: 'speed_click',
    durationMs: 15000,
    target: 200,
    reward: { expressPoints: 50, lootId: 'loot_speed_gloves' },
  },
  {
    id: 'no_click_1',
    name: 'Hands Off',
    description: 'Earn 10,000 packages without clicking for 60 seconds',
    icon: '\u{1F6AB}',
    type: 'no_click',
    durationMs: 60000,
    target: 10000,
    reward: { expressPoints: 15 },
  },
  {
    id: 'no_click_2',
    name: 'Full Automation',
    description: 'Earn 1,000,000 packages without clicking for 120 seconds',
    icon: '\u{1F916}',
    type: 'no_click',
    durationMs: 120000,
    target: 1000000,
    reward: { expressPoints: 40, lootId: 'loot_autopilot' },
  },
  {
    id: 'building_rush_1',
    name: 'Building Spree',
    description: 'Buy 10 buildings in 30 seconds',
    icon: '\u{1F3D7}\u{FE0F}',
    type: 'building_rush',
    durationMs: 30000,
    target: 10,
    reward: { expressPoints: 20 },
  },
  {
    id: 'building_rush_2',
    name: 'Construction Frenzy',
    description: 'Buy 25 buildings in 45 seconds',
    icon: '\u{1F3D7}\u{FE0F}',
    type: 'building_rush',
    durationMs: 45000,
    target: 25,
    reward: { expressPoints: 50, lootId: 'loot_hard_hat' },
  },
  {
    id: 'golden_hunt_1',
    name: 'Golden Hunt',
    description: 'Click 3 golden packages (no time limit, resets on fail)',
    icon: '\u{2B50}',
    type: 'golden_hunt',
    durationMs: 600000,
    target: 3,
    reward: { expressPoints: 30 },
  },
  {
    id: 'endurance_1',
    name: 'Marathon Runner',
    description: 'Maintain 100+ PPS for 5 minutes straight',
    icon: '\u{1F3C3}',
    type: 'endurance',
    durationMs: 300000,
    target: 100,
    reward: { expressPoints: 35, multiplierBonus: 0.05 },
  },
  {
    id: 'endurance_2',
    name: 'Unstoppable',
    description: 'Maintain 10,000+ PPS for 5 minutes straight',
    icon: '\u{1F525}',
    type: 'endurance',
    durationMs: 300000,
    target: 10000,
    reward: { expressPoints: 75, lootId: 'loot_eternal_flame' },
  },
];
