import { GameEvent } from '../models/game.models';

export const EVENT_DEFINITIONS: GameEvent[] = [
  // Positive (60%)
  {
    id: 'package_rush',
    name: 'Package Rush',
    description: 'FedEx Express priority surge! Production doubled across all stations!',
    icon: '\u{1F4E6}',
    type: 'positive',
    effect: { type: 'production_mult', value: 2 },
    durationMs: 30_000,
  },
  {
    id: 'express_delivery',
    name: 'FedEx Priority Overnight',
    description: 'When it absolutely, positively has to be clicked faster. +50% click value!',
    icon: '\u{26A1}',
    type: 'positive',
    effect: { type: 'click_mult', value: 1.5 },
    durationMs: 45_000,
  },
  {
    id: 'bulk_discount',
    name: 'Bulk Discount',
    description: 'FedEx corporate rate negotiated! Buildings cost 15% less.',
    icon: '\u{1F3F7}\u{FE0F}',
    type: 'positive',
    effect: { type: 'building_discount', value: 0.85 },
    durationMs: 60_000,
  },
  {
    id: 'tax_rebate',
    name: 'Fred Smith Bonus',
    description: 'The CEO himself returns 5% of your packages. "Old habits," he says.',
    icon: '\u{1F4B0}',
    type: 'positive',
    effect: { type: 'instant_packages', value: 0.05 },
    durationMs: 0,
  },
  {
    id: 'overtime_workers',
    name: 'Overtime at the Hub',
    description: 'Memphis hub workers pull overtime! A random building triples output.',
    icon: '\u{1F4AA}',
    type: 'positive',
    effect: { type: 'building_boost', value: 3 },
    durationMs: 30_000,
  },
  {
    id: 'shipping_surge',
    name: 'Peak Season Surge',
    description: 'Holiday season! Shipment volume boosts all production by 50%!',
    icon: '\u{1F6A2}',
    type: 'positive',
    effect: { type: 'production_mult', value: 1.5 },
    durationMs: 20_000,
  },

  // Negative (30%)
  {
    id: 'shipping_delay',
    name: 'Non-Compliant Trip',
    description: 'DEBRIEF flagged a non-compliant route! Production cut in half.',
    icon: '\u{1F6A7}',
    type: 'negative',
    effect: { type: 'production_mult', value: 0.5 },
    durationMs: 20_000,
  },
  {
    id: 'supply_chain_disruption',
    name: 'K-API Outage',
    description: 'The API is returning 500s! "It can be broken... but that is fine." Buildings cost 20% more.',
    icon: '\u{26D3}\u{FE0F}',
    type: 'negative',
    effect: { type: 'building_discount', value: 1.2 },
    durationMs: 30_000,
  },
  {
    id: 'lost_shipment',
    name: 'DEX 07 - Not Home',
    description: 'Customer not available! Shipment returned. You lose 1% of your packages.',
    icon: '\u{1F4ED}',
    type: 'negative',
    effect: { type: 'lose_packages', value: 0.01 },
    durationMs: 0,
  },
  {
    id: 'quality_inspection',
    name: 'Quality Audit',
    description: 'FedEx Quality Drive inspection. Station agents checking every scan. -25% production.',
    icon: '\u{1F50D}',
    type: 'negative',
    effect: { type: 'production_mult', value: 0.75 },
    durationMs: 15_000,
  },

  // Neutral (10%)
  {
    id: 'market_shift',
    name: 'Route Optimization',
    description: 'The Kaamelott Team deployed a new algorithm. One building booms, another busts.',
    icon: '\u{1F4CA}',
    type: 'neutral',
    effect: { type: 'production_mult', value: 1 },
    durationMs: 30_000,
  },
  {
    id: 'efficiency_review',
    name: 'System Maintenance',
    description: 'Brief K-API maintenance window then triple throughput! "Where the magic really happens!"',
    icon: '\u{1F4CB}',
    type: 'neutral',
    effect: { type: 'production_mult', value: 3 },
    durationMs: 20_000,
  },

  // Choice events
  {
    id: 'route_choice',
    name: 'Route Decision',
    description: 'Two routes available! The highway is safe, the shortcut is risky but rewarding.',
    icon: '\u{1F6E3}\u{FE0F}',
    type: 'neutral',
    effect: { type: 'player_choice', value: 0 },
    durationMs: 0,
    choices: [
      { label: 'Safe Highway (+20% prod, 30s)', effect: { type: 'production_mult', value: 1.2 }, durationMs: 30_000 },
      { label: 'Risky Shortcut (+80% prod, 15s)', effect: { type: 'production_mult', value: 1.8 }, durationMs: 15_000 },
    ],
  },
  {
    id: 'investment_choice',
    name: 'Investment Opportunity',
    description: 'A mysterious investor offers you a deal. What will you choose?',
    icon: '\u{1F4BC}',
    type: 'neutral',
    effect: { type: 'player_choice', value: 0 },
    durationMs: 0,
    choices: [
      { label: 'Cheap buildings (-20%, 60s)', effect: { type: 'building_discount', value: 0.8 }, durationMs: 60_000 },
      { label: 'Click power (+100%, 30s)', effect: { type: 'click_mult', value: 2 }, durationMs: 30_000 },
    ],
  },

  // Express Point events
  {
    id: 'express_bonus',
    name: 'Express Bonus',
    description: 'Priority mail rush! Earn bonus Express Points! +5 EP!',
    icon: '\u{1F48E}',
    type: 'positive',
    effect: { type: 'express_points', value: 5 },
    durationMs: 0,
  },
  {
    id: 'express_jackpot',
    name: 'Express Jackpot',
    description: 'VIP customer tips big! +15 Express Points!',
    icon: '\u{1F48E}',
    type: 'positive',
    effect: { type: 'express_points', value: 15 },
    durationMs: 0,
  },

  // Chain events
  {
    id: 'power_surge',
    name: 'Power Surge',
    description: 'Lightning strikes the hub! After a brief outage, everything runs at triple speed!',
    icon: '\u{26A1}',
    type: 'positive',
    effect: { type: 'production_mult', value: 3 },
    durationMs: 15_000,
  },
  {
    id: 'viral_moment',
    name: 'Viral Moment',
    description: 'Your package delivery goes viral on social media! Click power 5x for 20 seconds!',
    icon: '\u{1F4F1}',
    type: 'positive',
    effect: { type: 'click_mult', value: 5 },
    durationMs: 20_000,
  },
];
