import { LoreEntry } from '../models/game.models';

export const LORE_ENTRIES: LoreEntry[] = [
  {
    id: 'lore_origin',
    title: 'Chapter 1: The First Click',
    text: 'It started with a single click. A cardboard box appeared on your screen, and something deep inside you said: "I should click that." You did. And another appeared. And another. The packages were endless, and so was your curiosity.',
    icon: '\u{1F4E6}',
    requirement: { type: 'clicks', value: 1 },
  },
  {
    id: 'lore_trucks',
    title: 'Chapter 2: Wheels in Motion',
    text: 'Your first delivery truck rolled off the lot, exhaust puffing in the morning air. The driver looked at you, tipped his cap, and said: "Where to, boss?" You pointed at the horizon. "Everywhere."',
    icon: '\u{1F69A}',
    requirement: { type: 'buildings', value: 1, buildingType: 'cursor' },
  },
  {
    id: 'lore_sorting',
    title: 'Chapter 3: The Sorting Begins',
    text: 'The first sorting facility hummed to life. Conveyor belts whirred. Barcode scanners beeped their rhythmic song. A worker turned to you and said: "Where the magic really happens!" You believed them.',
    icon: '\u{1F3ED}',
    requirement: { type: 'buildings', value: 1, buildingType: 'grandma' },
  },
  {
    id: 'lore_growth',
    title: 'Chapter 4: The Growth',
    text: 'Ten thousand packages. Then a hundred thousand. The numbers climbed faster than you could count. Your empire was growing, and the world was starting to notice. A newspaper headline read: "Mystery Logistics Company Ships More Than Amazon."',
    icon: '\u{1F4C8}',
    requirement: { type: 'packages', value: 100000 },
  },
  {
    id: 'lore_golden',
    title: 'Chapter 5: The Golden Package',
    text: 'One morning, a shimmering golden package appeared. It was different. It pulsed with energy. When you clicked it, time itself seemed to slow. "Frenzy," whispered the package. And everything moved faster.',
    icon: '\u{2B50}',
    requirement: { type: 'clicks', value: 100 },
  },
  {
    id: 'lore_sky',
    title: 'Chapter 6: Taking to the Sky',
    text: 'Your first cargo plane took off from a makeshift airstrip. As it climbed into the clouds, you realized: the ground was no longer enough. The sky was your new highway. Memphis would be proud.',
    icon: '\u{2708}\u{FE0F}',
    requirement: { type: 'buildings', value: 1, buildingType: 'mine' },
  },
  {
    id: 'lore_million',
    title: 'Chapter 7: Millionaire',
    text: 'One million packages. You stared at the number, unblinking. Somewhere in a boardroom, Fred Smith himself raised an eyebrow. "Who IS this person?" he asked. Nobody answered. They were all clicking.',
    icon: '\u{1F4B0}',
    requirement: { type: 'packages', value: 1000000 },
  },
  {
    id: 'lore_prestige',
    title: 'Chapter 8: The Ascension',
    text: 'You pressed the button. Everything vanished — buildings, packages, upgrades. But something remained: experience. Knowledge. Heavenly points. You started again, but this time, you were different. You were faster.',
    icon: '\u{1F31F}',
    requirement: { type: 'prestige', value: 1 },
  },
  {
    id: 'lore_space',
    title: 'Chapter 9: Beyond the Atmosphere',
    text: 'The first rocket launched from your spaceport. Inside: ten thousand packages, bound for the International Space Station. The astronauts did not order them. They were delighted anyway. POD: scanned.',
    icon: '\u{1F680}',
    requirement: { type: 'buildings', value: 1, buildingType: 'spaceport' },
  },
  {
    id: 'lore_billion',
    title: 'Chapter 10: The Billion Box',
    text: 'One billion packages. If stacked, they would reach the moon. Twice. The UN declared you a sovereign nation. Your flag: a cardboard box on a field of purple.',
    icon: '\u{1F30D}',
    requirement: { type: 'packages', value: 1000000000 },
  },
  {
    id: 'lore_ceo',
    title: 'Chapter 11: Meeting Fred',
    text: '"I built FedEx with a college paper and a prayer," Fred Smith said, shaking your hand. "You built whatever THIS is with a mouse and determination. I think you might be crazier than me." You took that as a compliment.',
    icon: '\u{1F468}\u{200D}\u{1F4BC}',
    requirement: { type: 'buildings', value: 1, buildingType: 'ceo' },
  },
  {
    id: 'lore_kaamelott',
    title: 'Chapter 12: The Kaamelott Connection',
    text: '"C\'est pas faux," said the developer, staring at the API logs. The K-API had been returning 200 OK for three days straight — a new record. In the Package Clicker universe, this was cause for celebration. Champagne was opened. More packages were clicked.',
    icon: '\u{1F3F0}',
    requirement: { type: 'events', value: 10 },
  },
  {
    id: 'lore_satellite',
    title: 'Chapter 13: The Eye in the Sky',
    text: 'Your satellite network now tracks every package on Earth in real-time. DEBRIEF has gone orbital. Non-compliant trips can no longer hide behind cloud cover. The system sees all. The system delivers all.',
    icon: '\u{1F6F0}\u{FE0F}',
    requirement: { type: 'buildings', value: 1, buildingType: 'satellite' },
  },
  {
    id: 'lore_time',
    title: 'Chapter 14: Breaking Time',
    text: 'The first Time Machine hummed to life with a sound like tearing silk. You shipped a package to yesterday. The recipient left a review: "Received before I ordered. 5 stars." K-API response time went negative.',
    icon: '\u{231B}',
    requirement: { type: 'buildings', value: 1, buildingType: 'timemachine' },
  },
  {
    id: 'lore_multiverse',
    title: 'Chapter 15: Infinite Deliveries',
    text: 'The Multiverse Portal opened with a sound like reality hiccupping. Through it, you could see infinite versions of yourself, all clicking, all delivering. In every universe, the packages flow. In every universe, the clicking continues. It never stops. It never stops.',
    icon: '\u{1F30C}',
    requirement: { type: 'buildings', value: 1, buildingType: 'multiverse' },
  },
  {
    id: 'lore_trillion',
    title: 'Epilogue: The Trillion Ton',
    text: 'One trillion packages. The weight of your deliveries exceeds the mass of Mount Everest. Physicists write papers about you. Philosophers question the nature of clicking. You do not care. You click.',
    icon: '\u{1F451}',
    requirement: { type: 'packages', value: 1000000000000 },
  },
];
