import { HeavenlyUpgradeConfig, UpgradeEffect } from '../models/game.models';

export interface CorporateUpgradeConfig {
  id: string;
  name: string;
  description: string;
  price: number;
  icon: string;
  effects: UpgradeEffect[];
  requires: string[];
  position: { x: number; y: number };
}

export const HEAVENLY_UPGRADES: HeavenlyUpgradeConfig[] = [
  {
    id: 'hv_start',
    name: 'Heavenly Packages',
    description: 'You start with 10 packages after ascending',
    price: 1,
    icon: '📦',
    effects: [],
    requires: [],
    position: { x: 0, y: 0 },
  },
  {
    id: 'hv_cps1',
    name: 'Divine Logistics',
    description: '+5% packages per second',
    price: 2,
    icon: '⚡',
    effects: [{ type: 'global_multiplier', value: 1.05 }],
    requires: ['hv_start'],
    position: { x: -1, y: 1 },
  },
  {
    id: 'hv_cps2',
    name: 'Celestial Delivery',
    description: '+5% packages per second',
    price: 5,
    icon: '✨',
    effects: [{ type: 'global_multiplier', value: 1.05 }],
    requires: ['hv_cps1'],
    position: { x: -2, y: 2 },
  },
  {
    id: 'hv_click1',
    name: 'Heavenly Clicks',
    description: '+10% clicking power',
    price: 3,
    icon: '👆',
    effects: [{ type: 'click_multiplier', value: 1.1 }],
    requires: ['hv_start'],
    position: { x: 1, y: 1 },
  },
  {
    id: 'hv_click2',
    name: 'Divine Fingers',
    description: '+10% clicking power',
    price: 10,
    icon: '🤲',
    effects: [{ type: 'click_multiplier', value: 1.1 }],
    requires: ['hv_click1'],
    position: { x: 2, y: 2 },
  },
  {
    id: 'hv_cps3',
    name: 'Eternal Shipping',
    description: '+10% packages per second',
    price: 25,
    icon: '🌟',
    effects: [{ type: 'global_multiplier', value: 1.1 }],
    requires: ['hv_cps2'],
    position: { x: -3, y: 3 },
  },
  {
    id: 'hv_global1',
    name: 'Twin Gates',
    description: '+15% all production',
    price: 50,
    icon: '🌀',
    effects: [{ type: 'global_multiplier', value: 1.15 }],
    requires: ['hv_cps3', 'hv_click2'],
    position: { x: 0, y: 3 },
  },
  {
    id: 'hv_start2',
    name: 'Head Start',
    description: 'Start with 1,000 packages after ascending',
    price: 100,
    icon: '🎁',
    effects: [],
    requires: ['hv_global1'],
    position: { x: 0, y: 4 },
  },
  {
    id: 'hv_cps4',
    name: 'Omnipresent Delivery',
    description: '+15% packages per second',
    price: 200,
    icon: '🔮',
    effects: [{ type: 'global_multiplier', value: 1.15 }],
    requires: ['hv_start2'],
    position: { x: -1, y: 5 },
  },
  {
    id: 'hv_click3',
    name: 'Ascendant Click',
    description: '+25% clicking power',
    price: 200,
    icon: '💫',
    effects: [{ type: 'click_multiplier', value: 1.25 }],
    requires: ['hv_start2'],
    position: { x: 1, y: 5 },
  },
  {
    id: 'hv_global2',
    name: 'Cosmic Network',
    description: '+25% all production',
    price: 500,
    icon: '🌌',
    effects: [{ type: 'global_multiplier', value: 1.25 }],
    requires: ['hv_cps4', 'hv_click3'],
    position: { x: 0, y: 6 },
  },
  {
    id: 'hv_prestige1',
    name: 'Persistent Memory',
    description: 'Keep 10% of upgrades through ascension',
    price: 1000,
    icon: '🧠',
    effects: [],
    requires: ['hv_global2'],
    position: { x: -1, y: 7 },
  },
  {
    id: 'hv_cps5',
    name: 'Infinity Express',
    description: '+50% packages per second',
    price: 2000,
    icon: '♾️',
    effects: [{ type: 'global_multiplier', value: 1.5 }],
    requires: ['hv_global2'],
    position: { x: 1, y: 7 },
  },
  {
    id: 'hv_start3',
    name: 'Legacy Packages',
    description: 'Start with 100,000 packages after ascending',
    price: 5000,
    icon: '🏆',
    effects: [],
    requires: ['hv_prestige1', 'hv_cps5'],
    position: { x: 0, y: 8 },
  },
  {
    id: 'hv_final',
    name: 'Eternal Empire',
    description: '+100% all production',
    price: 10000,
    icon: '👑',
    effects: [{ type: 'global_multiplier', value: 2 }],
    requires: ['hv_start3'],
    position: { x: 0, y: 9 },
  },
];

// Corporate tier: requires timesAscended >= 3
export const CORPORATE_UPGRADES: CorporateUpgradeConfig[] = [
  {
    id: 'corp_stamp_speed',
    name: 'Express Stamps',
    description: 'Stamps generate 50% faster',
    price: 5,
    icon: '\uD83D\uDCEE',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: [],
    position: { x: 0, y: 0 },
  },
  {
    id: 'corp_employee_xp',
    name: 'Training Program',
    description: 'Employees gain 50% more XP',
    price: 5,
    icon: '\uD83C\uDFC5',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: [],
    position: { x: 2, y: 0 },
  },
  {
    id: 'corp_stock_insight',
    name: 'Market Insight',
    description: 'Stock volatility reduced by 20%',
    price: 8,
    icon: '\uD83D\uDCC8',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: ['corp_stamp_speed'],
    position: { x: -1, y: 1 },
  },
  {
    id: 'corp_offline',
    name: 'Night Shift',
    description: '+25% offline earnings',
    price: 8,
    icon: '\uD83C\uDF19',
    effects: [{ type: 'offline_mult', value: 1.25 }],
    requires: ['corp_employee_xp'],
    position: { x: 3, y: 1 },
  },
  {
    id: 'corp_golden',
    name: 'Golden Magnet',
    description: '+15% golden package frequency',
    price: 10,
    icon: '\uD83E\uDDF2',
    effects: [{ type: 'golden_frequency', value: 1.15 }],
    requires: ['corp_stamp_speed'],
    position: { x: 1, y: 1 },
  },
  {
    id: 'corp_research',
    name: 'R&D Division',
    description: 'Research completes 25% faster',
    price: 12,
    icon: '\uD83D\uDD2C',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: ['corp_stock_insight'],
    position: { x: -1, y: 2 },
  },
  {
    id: 'corp_fleet',
    name: 'Fleet Expansion',
    description: '+10% fleet route bonuses',
    price: 12,
    icon: '\uD83D\uDE9A',
    effects: [{ type: 'global_multiplier', value: 1.1 }],
    requires: ['corp_golden'],
    position: { x: 1, y: 2 },
  },
  {
    id: 'corp_ep_mult',
    name: 'Express Premium',
    description: '+20% Express Points earned',
    price: 15,
    icon: '\u26A1',
    effects: [{ type: 'express_point_mult', value: 1.2 }],
    requires: ['corp_offline'],
    position: { x: 3, y: 2 },
  },
  {
    id: 'corp_synergy',
    name: 'Corporate Synergy',
    description: '+15% all production',
    price: 20,
    icon: '\uD83D\uDD17',
    effects: [{ type: 'global_multiplier', value: 1.15 }],
    requires: ['corp_research', 'corp_fleet'],
    position: { x: 0, y: 3 },
  },
  {
    id: 'corp_click_power',
    name: 'Executive Click',
    description: '+30% clicking power',
    price: 20,
    icon: '\uD83D\uDC46',
    effects: [{ type: 'click_multiplier', value: 1.3 }],
    requires: ['corp_ep_mult'],
    position: { x: 2, y: 3 },
  },
  {
    id: 'corp_automation',
    name: 'Smart Automation',
    description: 'Automation rules run 50% faster',
    price: 25,
    icon: '\u2699',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: ['corp_synergy'],
    position: { x: 0, y: 4 },
  },
  {
    id: 'corp_kingdom',
    name: 'Kingdom Architect',
    description: 'Kingdom cities produce 25% more EP',
    price: 25,
    icon: '\uD83C\uDFDB',
    effects: [{ type: 'express_point_mult', value: 1.25 }],
    requires: ['corp_click_power'],
    position: { x: 2, y: 4 },
  },
  {
    id: 'corp_mega_mult',
    name: 'Mega Multiplier',
    description: '+25% all production',
    price: 50,
    icon: '\uD83D\uDD25',
    effects: [{ type: 'global_multiplier', value: 1.25 }],
    requires: ['corp_automation', 'corp_kingdom'],
    position: { x: 1, y: 5 },
  },
  {
    id: 'corp_prestige_boost',
    name: 'Prestige Amplifier',
    description: 'Each prestige level gives +2% instead of +1%',
    price: 75,
    icon: '\u2B50',
    effects: [{ type: 'global_multiplier', value: 1.0 }],
    requires: ['corp_mega_mult'],
    position: { x: 1, y: 6 },
  },
  {
    id: 'corp_final',
    name: 'Corporate Empire',
    description: '+100% all production',
    price: 100,
    icon: '\uD83C\uDFE2',
    effects: [{ type: 'global_multiplier', value: 2.0 }],
    requires: ['corp_prestige_boost'],
    position: { x: 1, y: 7 },
  },
];
