import { HeavenlyUpgradeConfig } from '../models/game.models';

export const HEAVENLY_UPGRADES: HeavenlyUpgradeConfig[] = [
  {
    id: 'hv_start',
    name: 'Heavenly Packages',
    description: 'You start with 10 packages after ascending',
    price: 1,
    icon: '📦',
    effects: [],
    requires: [],
    position: { x: 0, y: 0 },
  },
  {
    id: 'hv_cps1',
    name: 'Divine Logistics',
    description: '+5% packages per second',
    price: 2,
    icon: '⚡',
    effects: [{ type: 'global_multiplier', value: 1.05 }],
    requires: ['hv_start'],
    position: { x: -1, y: 1 },
  },
  {
    id: 'hv_cps2',
    name: 'Celestial Delivery',
    description: '+5% packages per second',
    price: 5,
    icon: '✨',
    effects: [{ type: 'global_multiplier', value: 1.05 }],
    requires: ['hv_cps1'],
    position: { x: -2, y: 2 },
  },
  {
    id: 'hv_click1',
    name: 'Heavenly Clicks',
    description: '+10% clicking power',
    price: 3,
    icon: '👆',
    effects: [{ type: 'click_multiplier', value: 1.1 }],
    requires: ['hv_start'],
    position: { x: 1, y: 1 },
  },
  {
    id: 'hv_click2',
    name: 'Divine Fingers',
    description: '+10% clicking power',
    price: 10,
    icon: '🤲',
    effects: [{ type: 'click_multiplier', value: 1.1 }],
    requires: ['hv_click1'],
    position: { x: 2, y: 2 },
  },
  {
    id: 'hv_cps3',
    name: 'Eternal Shipping',
    description: '+10% packages per second',
    price: 25,
    icon: '🌟',
    effects: [{ type: 'global_multiplier', value: 1.1 }],
    requires: ['hv_cps2'],
    position: { x: -3, y: 3 },
  },
  {
    id: 'hv_global1',
    name: 'Twin Gates',
    description: '+15% all production',
    price: 50,
    icon: '🌀',
    effects: [{ type: 'global_multiplier', value: 1.15 }],
    requires: ['hv_cps3', 'hv_click2'],
    position: { x: 0, y: 3 },
  },
  {
    id: 'hv_start2',
    name: 'Head Start',
    description: 'Start with 1,000 packages after ascending',
    price: 100,
    icon: '🎁',
    effects: [],
    requires: ['hv_global1'],
    position: { x: 0, y: 4 },
  },
  {
    id: 'hv_cps4',
    name: 'Omnipresent Delivery',
    description: '+15% packages per second',
    price: 200,
    icon: '🔮',
    effects: [{ type: 'global_multiplier', value: 1.15 }],
    requires: ['hv_start2'],
    position: { x: -1, y: 5 },
  },
  {
    id: 'hv_click3',
    name: 'Ascendant Click',
    description: '+25% clicking power',
    price: 200,
    icon: '💫',
    effects: [{ type: 'click_multiplier', value: 1.25 }],
    requires: ['hv_start2'],
    position: { x: 1, y: 5 },
  },
  {
    id: 'hv_global2',
    name: 'Cosmic Network',
    description: '+25% all production',
    price: 500,
    icon: '🌌',
    effects: [{ type: 'global_multiplier', value: 1.25 }],
    requires: ['hv_cps4', 'hv_click3'],
    position: { x: 0, y: 6 },
  },
  {
    id: 'hv_prestige1',
    name: 'Persistent Memory',
    description: 'Keep 10% of upgrades through ascension',
    price: 1000,
    icon: '🧠',
    effects: [],
    requires: ['hv_global2'],
    position: { x: -1, y: 7 },
  },
  {
    id: 'hv_cps5',
    name: 'Infinity Express',
    description: '+50% packages per second',
    price: 2000,
    icon: '♾️',
    effects: [{ type: 'global_multiplier', value: 1.5 }],
    requires: ['hv_global2'],
    position: { x: 1, y: 7 },
  },
  {
    id: 'hv_start3',
    name: 'Legacy Packages',
    description: 'Start with 100,000 packages after ascending',
    price: 5000,
    icon: '🏆',
    effects: [],
    requires: ['hv_prestige1', 'hv_cps5'],
    position: { x: 0, y: 8 },
  },
  {
    id: 'hv_final',
    name: 'Eternal Empire',
    description: '+100% all production',
    price: 10000,
    icon: '👑',
    effects: [{ type: 'global_multiplier', value: 2 }],
    requires: ['hv_start3'],
    position: { x: 0, y: 9 },
  },
];
