import { RareLootConfig } from '../models/game.models';

export const RARE_LOOT_DEFINITIONS: RareLootConfig[] = [
  // Common drops (from golden packages)
  {
    id: 'loot_lucky_penny',
    name: 'Lucky Penny',
    description: '+1% all production permanently',
    icon: '\u{1FA99}',
    rarity: 'common',
    effect: { type: 'global_multiplier', value: 1.01 },
    dropWeight: 40,
  },
  {
    id: 'loot_fast_fingers',
    name: 'Fast Fingers',
    description: '+2% click power permanently',
    icon: '\u{1F446}',
    rarity: 'common',
    effect: { type: 'click_multiplier', value: 1.02 },
    dropWeight: 35,
  },
  {
    id: 'loot_coupon',
    name: 'FedEx Coupon',
    description: 'Buildings cost 1% less permanently',
    icon: '\u{1F3AB}',
    rarity: 'common',
    effect: { type: 'building_cost_reduction', value: 0.99 },
    dropWeight: 25,
  },
  // Uncommon drops
  {
    id: 'loot_turbo_belt',
    name: 'Turbo Conveyor Belt',
    description: '+5% all production permanently',
    icon: '\u{2699}\u{FE0F}',
    rarity: 'uncommon',
    effect: { type: 'global_multiplier', value: 1.05 },
    dropWeight: 15,
  },
  {
    id: 'loot_barcode',
    name: 'Golden Barcode',
    description: '+5% click power permanently',
    icon: '\u{1F4F2}',
    rarity: 'uncommon',
    effect: { type: 'click_multiplier', value: 1.05 },
    dropWeight: 12,
  },
  {
    id: 'loot_express_card',
    name: 'Express Card',
    description: '+50% Express Points earned',
    icon: '\u{1F4B3}',
    rarity: 'uncommon',
    effect: { type: 'express_point_mult', value: 1.5 },
    dropWeight: 8,
  },
  // Rare drops
  {
    id: 'loot_freds_hat',
    name: 'Fred\'s Lucky Hat',
    description: '+10% all production permanently',
    icon: '\u{1F3A9}',
    rarity: 'rare',
    effect: { type: 'global_multiplier', value: 1.10 },
    dropWeight: 5,
  },
  {
    id: 'loot_pod_scanner',
    name: 'Quantum POD Scanner',
    description: '+15% click power permanently',
    icon: '\u{1F4F1}',
    rarity: 'rare',
    effect: { type: 'click_multiplier', value: 1.15 },
    dropWeight: 4,
  },
  // Epic drops (from challenges)
  {
    id: 'loot_speed_gloves',
    name: 'Speed Gloves',
    description: '+20% click power permanently',
    icon: '\u{1F9E4}',
    rarity: 'epic',
    effect: { type: 'click_multiplier', value: 1.20 },
    dropWeight: 0,
  },
  {
    id: 'loot_autopilot',
    name: 'Autopilot Module',
    description: '+25% offline earnings permanently',
    icon: '\u{1F916}',
    rarity: 'epic',
    effect: { type: 'offline_mult', value: 0.25 },
    dropWeight: 0,
  },
  {
    id: 'loot_hard_hat',
    name: 'Golden Hard Hat',
    description: 'Buildings cost 5% less permanently',
    icon: '\u{26D1}\u{FE0F}',
    rarity: 'epic',
    effect: { type: 'building_cost_reduction', value: 0.95 },
    dropWeight: 0,
  },
  {
    id: 'loot_eternal_flame',
    name: 'Eternal Flame',
    description: '+25% all production permanently',
    icon: '\u{1F525}',
    rarity: 'epic',
    effect: { type: 'global_multiplier', value: 1.25 },
    dropWeight: 0,
  },
  // Legendary drops (very rare from golden packages)
  {
    id: 'loot_holy_grail',
    name: 'The Holy Grail',
    description: '+50% all production permanently. "C\'est pas faux."',
    icon: '\u{1F3C6}',
    rarity: 'legendary',
    effect: { type: 'global_multiplier', value: 1.50 },
    dropWeight: 1,
  },
  {
    id: 'loot_freds_dice',
    name: 'Fred\'s Lucky Dice',
    description: 'Golden packages appear 50% more often',
    icon: '\u{1F3B2}',
    rarity: 'legendary',
    effect: { type: 'golden_frequency', value: 0.5 },
    dropWeight: 1,
  },
];
