import { ResearchNode } from '../models/game.models';

export const RESEARCH_NODES: ResearchNode[] = [
  // ── Logistics branch (x=0, global_multiplier / PPS focus) ──
  {
    id: 'log_1',
    name: 'Efficient Routes',
    description: 'Optimise delivery paths for a 3% production boost.',
    icon: '\uD83D\uDEE3\uFE0F',
    branch: 'logistics',
    cost: { ep: 10, timeMs: 60_000 },
    effects: [{ type: 'global_multiplier', value: 1.03 }],
    requires: [],
    position: { x: 0, y: 0 },
  },
  {
    id: 'log_2',
    name: 'Bulk Shipping',
    description: 'Ship larger batches for a 5% production boost.',
    icon: '\uD83D\uDE9A',
    branch: 'logistics',
    cost: { ep: 25, timeMs: 120_000 },
    effects: [{ type: 'global_multiplier', value: 1.05 }],
    requires: ['log_1'],
    position: { x: 0, y: 1 },
  },
  {
    id: 'log_3',
    name: 'Smart Sorting',
    description: 'AI-driven sorting for an 8% production boost.',
    icon: '\uD83E\uDDE0',
    branch: 'logistics',
    cost: { ep: 50, timeMs: 180_000 },
    effects: [{ type: 'global_multiplier', value: 1.08 }],
    requires: ['log_2'],
    position: { x: 0, y: 2 },
  },
  {
    id: 'log_4',
    name: 'Quantum Logistics',
    description: 'Teleport packages for a 12% production boost.',
    icon: '\u269B\uFE0F',
    branch: 'logistics',
    cost: { ep: 100, timeMs: 300_000 },
    effects: [{ type: 'global_multiplier', value: 1.12 }],
    requires: ['log_3'],
    position: { x: 0, y: 3 },
  },
  {
    id: 'log_5',
    name: 'Hyperdrive Delivery',
    description: 'Faster-than-light shipping for a 20% production boost.',
    icon: '\uD83D\uDE80',
    branch: 'logistics',
    cost: { ep: 200, timeMs: 600_000 },
    effects: [{ type: 'global_multiplier', value: 1.20 }],
    requires: ['log_4'],
    position: { x: 0, y: 4 },
  },

  // ── Engineering branch (x=1, click_multiplier focus) ──
  {
    id: 'eng_1',
    name: 'Reinforced Clicks',
    description: 'Strengthen your clicks by 5%.',
    icon: '\uD83D\uDD27',
    branch: 'engineering',
    cost: { ep: 10, timeMs: 60_000 },
    effects: [{ type: 'click_multiplier', value: 1.05 }],
    requires: [],
    position: { x: 1, y: 0 },
  },
  {
    id: 'eng_2',
    name: 'Precision Tapping',
    description: 'Calibrated clicks for an 8% boost.',
    icon: '\uD83D\uDD2C',
    branch: 'engineering',
    cost: { ep: 25, timeMs: 120_000 },
    effects: [{ type: 'click_multiplier', value: 1.08 }],
    requires: ['eng_1'],
    position: { x: 1, y: 1 },
  },
  {
    id: 'eng_3',
    name: 'Hydraulic Press',
    description: 'Industrial-grade clicking for a 12% boost.',
    icon: '\uD83C\uDFED',
    branch: 'engineering',
    cost: { ep: 50, timeMs: 180_000 },
    effects: [{ type: 'click_multiplier', value: 1.12 }],
    requires: ['eng_2'],
    position: { x: 1, y: 2 },
  },
  {
    id: 'eng_4',
    name: 'Atomic Clicks',
    description: 'Split atoms with each click for an 18% boost.',
    icon: '\u2622\uFE0F',
    branch: 'engineering',
    cost: { ep: 100, timeMs: 300_000 },
    effects: [{ type: 'click_multiplier', value: 1.18 }],
    requires: ['eng_3'],
    position: { x: 1, y: 3 },
  },
  {
    id: 'eng_5',
    name: 'Quantum Finger',
    description: 'Click in all dimensions for a 25% boost.',
    icon: '\uD83E\uDD1E',
    branch: 'engineering',
    cost: { ep: 200, timeMs: 600_000 },
    effects: [{ type: 'click_multiplier', value: 1.25 }],
    requires: ['eng_4'],
    position: { x: 1, y: 4 },
  },

  // ── Finance branch (x=2, express_point_mult focus) ──
  {
    id: 'fin_1',
    name: 'Tax Breaks',
    description: 'Earn 5% more Express Points.',
    icon: '\uD83D\uDCB0',
    branch: 'finance',
    cost: { ep: 15, timeMs: 90_000 },
    effects: [{ type: 'express_point_mult', value: 1.05 }],
    requires: [],
    position: { x: 2, y: 0 },
  },
  {
    id: 'fin_2',
    name: 'Venture Capital',
    description: 'Investors boost EP earnings by 8%.',
    icon: '\uD83D\uDCC8',
    branch: 'finance',
    cost: { ep: 30, timeMs: 150_000 },
    effects: [{ type: 'express_point_mult', value: 1.08 }],
    requires: ['fin_1'],
    position: { x: 2, y: 1 },
  },
  {
    id: 'fin_3',
    name: 'Market Analysis',
    description: 'Data-driven decisions for 12% more EP.',
    icon: '\uD83D\uDCCA',
    branch: 'finance',
    cost: { ep: 60, timeMs: 240_000 },
    effects: [{ type: 'express_point_mult', value: 1.12 }],
    requires: ['fin_2'],
    position: { x: 2, y: 2 },
  },
  {
    id: 'fin_4',
    name: 'Hedge Funds',
    description: 'Algorithmic trading for 18% more EP.',
    icon: '\uD83E\uDDEE',
    branch: 'finance',
    cost: { ep: 120, timeMs: 360_000 },
    effects: [{ type: 'express_point_mult', value: 1.18 }],
    requires: ['fin_3'],
    position: { x: 2, y: 3 },
  },
  {
    id: 'fin_5',
    name: 'Infinite Money',
    description: 'Money printer goes brrr \u2014 25% more EP.',
    icon: '\uD83D\uDCB8',
    branch: 'finance',
    cost: { ep: 250, timeMs: 600_000 },
    effects: [{ type: 'express_point_mult', value: 1.25 }],
    requires: ['fin_4'],
    position: { x: 2, y: 4 },
  },

  // ── Innovation branch (x=3, misc boosts) ──
  {
    id: 'inn_1',
    name: 'Lucky Charm',
    description: 'Golden packages appear 5% more often.',
    icon: '\uD83C\uDF40',
    branch: 'innovation',
    cost: { ep: 15, timeMs: 90_000 },
    effects: [{ type: 'golden_frequency', value: 1.05 }],
    requires: [],
    position: { x: 3, y: 0 },
  },
  {
    id: 'inn_2',
    name: 'Night Shift',
    description: 'Earn 10% more while offline.',
    icon: '\uD83C\uDF19',
    branch: 'innovation',
    cost: { ep: 30, timeMs: 150_000 },
    effects: [{ type: 'offline_mult', value: 1.10 }],
    requires: ['inn_1'],
    position: { x: 3, y: 1 },
  },
  {
    id: 'inn_3',
    name: 'Double Down',
    description: 'Golden packages appear 10% more often.',
    icon: '\uD83C\uDFB2',
    branch: 'innovation',
    cost: { ep: 60, timeMs: 240_000 },
    effects: [{ type: 'golden_frequency', value: 1.10 }],
    requires: ['inn_2'],
    position: { x: 3, y: 2 },
  },
  {
    id: 'inn_4',
    name: 'Time Warp',
    description: 'Bend time for 20% more offline earnings.',
    icon: '\u231B',
    branch: 'innovation',
    cost: { ep: 120, timeMs: 360_000 },
    effects: [{ type: 'offline_mult', value: 1.20 }],
    requires: ['inn_3'],
    position: { x: 3, y: 3 },
  },
  {
    id: 'inn_5',
    name: 'Singularity',
    description: 'All converges \u2014 +15% production and +15% clicks.',
    icon: '\uD83C\uDF1F',
    branch: 'innovation',
    cost: { ep: 250, timeMs: 600_000 },
    effects: [
      { type: 'global_multiplier', value: 1.15 },
      { type: 'click_multiplier', value: 1.15 },
    ],
    requires: ['inn_4'],
    position: { x: 3, y: 4 },
  },
];
